### ISSUE TITLE
create certmonger rule

### ISSUE THREAD

**Issue by databang-io** [WAGO/pfc-firmware-sdk-G2#1]
Hi,
I'm currently trying to create a new package for certmonger-0.79.15

https://pagure.io/certmonger 

It is an utility to manager certificate lifecycle via SCEP .
I have contacted WAGO belgium but they have refered me to this git repo  .

I'm currently stuck with one of the dependancies talloc 

I need to have this feature implemented on all our PFC plc for NIST compliance .

Any assitance would be really apreciated  .

Bernard Rodriguez

bernard.rodriguez@infrabel.be

**Comment by Thomas-Brandt** [comment]
Hi Bernard,

as you already know please take a look at:
[HowTo_AddCertmonger](https://github.com/WAGO/pfc-howtos/tree/master/HowTo_AddCertmonger)

BR,
Thomas
