### ISSUE TITLE
PFC200 (750-8217,-8212,-8210) FW27 WBM bugs

### ISSUE THREAD

**Issue by ruzickaRVTECH** [WAGO/pfc-firmware-sdk-G2#14]
Hi,
I found bugs at "wbm/#/security/firewall/interface-configuration". All PLCs from titles have some bugs there. Just 8212, 8210 were factory new.

8212, 8210 - can't change VPN firewall. After i change firewall, everything reverse back to "default" state (just BACnet/IP (udp/tcp, port 47808))
8217 - immediately after page with FW interfaces loads, there is warning with error "Failed to read the values
Errors occurred while reading the parameters for the current page" and WAN interface has bad labels. There is same issue like as in other PLC with VPN firewall interface, but there is different setting by "default"
![image](https://github.com/user-attachments/assets/9e8c7382-36db-4dad-b4da-5b83a3b43144) 
![image](https://github.com/user-attachments/assets/75cbef43-1e32-4867-9e70-9688ed0c70d0)

I also found same problems on CC100-9301.
Also OVPN connecting takes much longer than on FW26, were there some changes?

**Comment by dicksimon** [comment]
Hello @ruzickaRVTECH,
I was not able to reproduce the behaviour on our 8212 controller. Did you only follow the basic instructions or modify the sources?

**Comment by ruzickaRVTECH** [comment]
@dicksimon 
I was updating FW with WAGOupload (v1.17) maybe that could cause some problems because it is older version. I will try to update another PLC soon with newer version of WAGOupload if problems will remain. FW was downloaded not from git but from WAGOdownload site

another thing that happened to all PLCs... I was unable to do factory reset with WAGO Ethernet Settings, because app didn't even find PLCs via ethernet. I did factory reset with RST button and it looks much better. I didn't test it as much as in previous case, but atleast WBM firewall settings looks ok now and PLCs are visible from all aps I tried.

**Comment by dicksimon** [comment]
> I was updating FW with WAGOupload (v1.17) maybe that could cause some problems because it is older version. I will try to update another PLC soon with newer version of WAGOupload if problems will remain

Okay, let me know if the problem still exists. If so, please provide the firmware revision of your starting point for further investigations. 

> another thing that happened to all PLCs... I was unable to do factory reset with WAGO Ethernet Settings, because app didn't even find PLCs via ethernet. I did factory reset with RST button and it looks much better. I didn't test it as much as in previous case, but atleast WBM firewall settings looks ok now and PLCs are visible from all aps I tried.

As above, if the problem remains please provide the firmware revision of your starting point. 

> I also found same problems on CC100-9301.

Please use this [repository](https://github.com/WAGO/cc100-firmware-sdk) for issues related to the CC100 family. In general, one issue per problem is the appropriate way to track multiple issues.

**Comment by dicksimon** [comment]
I will close this issue for now. If you have any updates, please reopen this issue or create a more specific one.
