### ISSUE TITLE
m4 Error: SIGSTKSZ => add m4 patch"04-fix-sigstksz.patch" 

### ISSUE THREAD

**Issue by ghost** [WAGO/pfc-firmware-sdk-G2#4]
Hello,

after cloning the repo and setting up the build env there is a error with m4

After 
`ptxdist go`

> make[3]: Entering directory '/home/XX/wago/ptxproj/platform-wago-pfcXXX/build-host/m4-1.4.18/lib'
  CC       gl_avltree_oset.o
  CC       binary-io.o
  CC       c-ctype.o
  CC       c-stack.o
  CC       c-strcasecmp.o
  CC       c-strncasecmp.o
  CC       clean-temp.o
  CC       cloexec.o
  CC       close-stream.o
  CC       closein.o
  CC       closeout.o
  CC       basename.o
  CC       dirname.o
  CC       dirname-lgpl.o
  CC       basename-lgpl.o
  CC       stripslash.o
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
  CC       execute.o
make[3]: *** [Makefile:1910: c-stack.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC       exitfail.o
  CC       fatal-signal.o
make[3]: Leaving directory '/home/XX/wago/ptxproj/platform-wago-pfcXXX/build-host/m4-1.4.18/lib'
make[2]: *** [Makefile:1674: all] Error 2
make[2]: Leaving directory '/home/XX/wago/ptxproj/platform-wago-pfcXXX/build-host/m4-1.4.18/lib'
make[1]: *** [Makefile:1572: all-recursive] Error 1
make[1]: Leaving directory '/home/XX/wago/ptxproj/platform-wago-pfcXXX/build-host/m4-1.4.18'
make: *** [Makefile:1528: all] Error 2
make: Leaving directory '/home/XX/wago/ptxproj/platform-wago-pfcXXX/build-host/m4-1.4.18'
make: *** [/usr/local/lib/ptxdist-2020.08.0/rules/post/ptxd_make_world_compile.make:20: /home/XX/wago/ptxproj/platform-wago-pfcXXX/state/host-m4.compile] Error 2

The error is described here
[https://github.com/openwrt/openwrt/issues/9055](https://github.com/openwrt/openwrt/issues/9055)

To resolve:
Add the file 04-fix-sigstksz.patch to /patches/m4.../ and update series file to include patch

**Comment by falk-werner** [comment]
Thanks a lot for your finding.
I had problems to reproduce the issue with our Ubuntu 16,04 ESM build environment. Can you please describe, which environment you are using?

**Comment by falk-werner** [comment]
Since we were unable to reproduce the issue in our environment, we did not add the patch for firmware 24 SDK.
Starting with the upcoming firmware 25 SDK (no release date scheduled yet), we will switch to a later version of this package.
