### ISSUE TITLE
Error on ptxdist images

### ISSUE THREAD

**Issue by DBREngineer** [WAGO/pfc-firmware-sdk-G2#7]
Hello,

I get this error messages on compiling for Firmware 24 with ptxdist images:

`
Configuring sfp-tool.
 * cds3-tscexttask
 * check_data_file_clashes: Package dalshell wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/etc/specific/pfc_batch_process.conf.0x004E
	But that file is already provided by package  * cds3-tscexttask
 * check_data_file_clashes: Package dalshell wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/sbin/dalshell
	But that file is already provided by package  * cds3-tscexttask
 * opkg_solver_install: Cannot install package dalshell.
 * check_data_file_clashes: Package cds3-tscsysprocessorload wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/etc/codesys3.d/TscSysProcessorLoad.cfg
	But that file is already provided by package  * cds3-tscmodbus
 * check_data_file_clashes: Package cds3-tscsysprocessorload wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/cds3-custom-components/libTscSysProcessorLoad.so
	But that file is already provided by package  * cds3-tscmodbus
 * check_data_file_clashes: Package cds3-tscsysprocessorload wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/libTscSysProcessorLoad.so
	But that file is already provided by package  * cds3-tscmodbus
 * check_data_file_clashes: Package cds3-tscsysprocessorload wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/libTscSysProcessorLoad.so.0.0.1
	But that file is already provided by package  * cds3-tscmodbus
 * opkg_solver_install: Cannot install package cds3-tscsysprocessorload.
 * check_data_file_clashes: Package canopen wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/cds3-custom-components/libTscComSwitch.so
	But that file is already provided by package  * cds3-tscsyssqlite
 * check_data_file_clashes: Package canopen wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/libTscComSwitch.so
	But that file is already provided by package  * cds3-tscsyssqlite
 * check_data_file_clashes: Package canopen wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/libTscComSwitch.so.0.0.4
	But that file is already provided by package  * cds3-tscsyssqlite
 * check_data_file_clashes: Package cds3-iodrvcanl2 wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/IoDrvDal/libIoDrvCanL2.so
	But that file is already provided by package  * cds3-iodrvkbus
 * check_data_file_clashes: Package cds3-iodrvcanl2 wants to install file /home/user/ptxproj/platform-wago-pfcXXX/build-target/image-root-tgz/usr/lib/libIoDrvCanL2.so.1.0.2
	But that file is already provided by package  * cds3-iodrvkbus
 * opkg_solver_install: Cannot install package cds3-iodrvcanl2.
make: *** [/home/user/ptxproj/rules/image-root-tgz.make:37: /home/user/ptxproj/platform-wago-pfcXXX/images/root.tgz] Error 255
`

Any help available?

Thanks,

Thomas

**Comment by falk-werner** [comment]
It seems that you tried to build the packages in parallel using ptxdist's `-j` option, did you?

Unfortunately, parallel build is not supported at the moment due to a design decision regarding handling of closed-source packages. To solve the problem, you need to `ptxdist clean` your workspace and re-build. You may use ptxdist's `--j-intern` option to speed up the build.

**Comment by DBREngineer** [comment]
Thanks,
this helped!
