### ISSUE TITLE
"make builder" for FW 22 doesn't work

### ISSUE THREAD

**Issue by DBREngineer** [WAGO/pfc-firmware-sdk-G2#8]
Hi,

I checked out FW22.

make builder returns:

`thomas@wagofw-vbox:~/wago_fw22$ make builder
make: ptxdist: Datei oder Verzeichnis nicht gefunden
cat: /etc/REVISIONS: Datei oder Verzeichnis nicht gefunden
make: ptxdist: Datei oder Verzeichnis nicht gefunden
cat: /etc/SVNREVISION: Datei oder Verzeichnis nicht gefunden
make: ptxdist: Datei oder Verzeichnis nicht gefunden
Makefile:320: *** PTXdist platform not configured.  Schluss.`

Thanks for your help.

**Comment by falk-werner** [comment]
Your observation is correct: the new docker-based build process cannot be used for FW22 yet.
The docker-based build process requires a specific project layout and FW22 is not prepared for this yet. Also note, that FW22's build environment differs from the SDK-builder (Ubuntu 16.04 vs. Ubuntu 20.04, Linaro 2019.12 toolchain [GCC 9.2] vs. Linaro 2020.02 [GCC11.2] toolchain).

We intend to introduce the docker-based build process with the next update of FW22 (release date is not scheduled yet). Please use the VM-based build process for FW22 until then.
