### ISSUE TITLE
Required version Ubuntu for BSP?

### ISSUE THREAD

**Issue by sjoerdboerhout** [WAGO/pfc-firmware-sdk-G2#9]
I noticed the updated instruction to setup the SDK build environment. 

The previous readme file was pretty clear about the Linux version required (Ubuntu 16.04). The new manual doesn't mention any details about the host system to run the docker image.
Depending on the chapter 'PREREQUISITES' it still seems to be Linux, but is there any specific version I have to use or can I just use the latest Ubuntu version?

Currently we are using the Ubuntu 16.04 with toolchain 2019

**Comment by dicksimon** [comment]
As our new SDK workflow uses docker, there is no need to use a specific Linux distribution. The base image ([sdk-builder](https://github.com/WAGO/sdk-builder)) for our SDKs already includes Ubuntu 20.04 and the correct toolchain. Just follow the instructions in the manual and you will be fine.

We will also add a hint in the manual with our next release.

**Comment by dicksimon** [comment]
I will close this issue. If you have any further questions just reopen the issue.
